### ISSUE TITLE
Wrong layout for self-loop edge

### ISSUE THREAD

**Issue by lredor** [eclipse/elk#425]
The layout of self loop edge is wrong when using org.eclipse.elk.layered algoriythm. It seems shifted with the coordinates of its container.

Steps to reproduce:
* Open SampleWithEdgeInsideSelfLoop.elkg in the Layout Graph view (from [SampleWithEdgeInsideSelfLoop.zip](https://github.com/eclipse/elk/files/3211106/SampleWithEdgeInsideSelfLoop.zip)). The initial graph, without layout, is like
![SampleWithEdgeInsideSelfLoop-initial](https://user-images.githubusercontent.com/1825882/58238032-c0f56080-7d46-11e9-83c9-cc725ad10f18.png)
* The layout result is like this graph
 ![SampleWithEdgeInsideSelfLoop-result](https://user-images.githubusercontent.com/1825882/58238030-c0f56080-7d46-11e9-9f62-b44ebdf1c237.png)
The coordinates of the edge is
```
  <sections startX="27.0" startY="47.0" endX="49.0" endY="47.0">
    <bendPoints x="26.999999999999996" y="37.0"/>
    <bendPoints x="49.0" y="37.0"/>
  </sections>
```
* But the expected result is like this graph
![SampleWithEdgeInsideSelfLoop-expected](https://user-images.githubusercontent.com/1825882/58238031-c0f56080-7d46-11e9-99bf-b843af3edde9.png)
The coordinates should be shifted with its container coordinates `{5.0, 47.0}`.
```
  <sections startX="22.0" startY="0.0" endX="44.0" endY="0.0">
    <bendPoints x="21.999999999999996" y="37.0"/>
    <bendPoints x="44.0" y="37.0"/>
  </sections>
```

This issue is maybe linked to [ELK#420](https://github.com/eclipse/elk/issues/420).

**Comment by le-cds** [comment]
Fixed as soon as #446 is on master.

**Comment by lredor** [comment]
This issue is not resolved. The result is different but is not OK:
![CurrentResultOnMaster](https://user-images.githubusercontent.com/1825882/71262251-8e90fd80-233f-11ea-8b13-46b3dd20b700.png)

**Comment by le-cds** [comment]
@lredor This is strange. At least with what's currently on the master, I'm getting this result:

![result](https://user-images.githubusercontent.com/7465584/74031099-f2838a00-49b0-11ea-83a3-99d2a8b701c9.png)

Please verify the results you're getting. I'm reopening the issue until I have confirmation that the bug doesn't exist anymore, or that I need to take another look.

**Comment by lredor** [comment]
I verified and the problem is always here. I searched to understand why you have not the same result. With the elkg file in the zip file of description, the result is:
![originalUseCase](https://user-images.githubusercontent.com/1825882/74044786-ef49c780-49cb-11ea-8981-f6d997aad889.png)

In this file, the edge is contained in the Node1. That seems normal as both source and target are "in" the node. I updated the sample to have the edge contained in the Container1. And with this version, I have the same result as you:
![updatedUseCase](https://user-images.githubusercontent.com/1825882/74044834-05578800-49cc-11ea-8a46-7e0f3165923b.png)

My question: Does an inside loop edge "must" be contained in the container of the node and not directly in the node? If the answer is "Yes", you can close this issue, the problem is in the structure of the graph. If the answer is "No", there is probably a bug in the code for this case.

The 2 versions of the elkg is in this file SampleWithEdgeInsideSelfLoop-2versions.zip:
[SampleWithEdgeInsideSelfLoop-2versions.zip](https://github.com/eclipse/elk/files/4171770/SampleWithEdgeInsideSelfLoop-2versions.zip)

**Comment by le-cds** [comment]
That is the problem indeed: self loops must be contained in the parent of the node the self loops loops around. `ElkGraphUtil.updateContainment(...)` can help find the proper containment for edges. I've updated the documentation to include a paragraph on where self loops are contained.
